// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPiat8m76WQ7ebYdlEfCoDMkrokpGBBIU',
    appId: '1:860023115896:web:7fd9220c34bd181b4f1d8d',
    messagingSenderId: '860023115896',
    projectId: 'strawberry-db-536df',
    authDomain: 'strawberry-db-536df.firebaseapp.com',
    storageBucket: 'strawberry-db-536df.firebasestorage.app',
    measurementId: 'G-J0RZ701VRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC47sHXokTa24J0RB1pA_C_apmWl0CE65A',
    appId: '1:860023115896:android:7221c8f2806df7e94f1d8d',
    messagingSenderId: '860023115896',
    projectId: 'strawberry-db-536df',
    storageBucket: 'strawberry-db-536df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOAqDBE_FRFPKhfHIqYqriCU5A6iTQlgY',
    appId: '1:860023115896:ios:ed05a14fa80c98524f1d8d',
    messagingSenderId: '860023115896',
    projectId: 'strawberry-db-536df',
    storageBucket: 'strawberry-db-536df.firebasestorage.app',
    iosBundleId: 'com.example.strawberryDiseaseDetection',
  );
}
